### ISSUE TITLE
Application blocked due to large amount of logs generated

### ISSUE THREAD

**Issue by sfc-gh-atoader** [TheParmak/forage-jpmc-cyber-3#1]
Hi @TheParmak!

I am an engineer on Streamlit Community Cloud. We had to spin down the application deployed from one of your repositories because it was generating a very large amount of logs 14M in 1h.

Let me know once you've cleaned up your code and I will unblock your account.

Alex

**Comment by TheParmak** [comment]
Sorry for the mess lol, i cleaned it up now. Could you please unblock it?

**Comment by sfc-gh-atoader** [comment]
Done! :) Thank you!
